name="flash"
compatibility_date="2024-04-15"

[vars]
UPSTASH_REDIS_REST_TOKEN = "AZb-ASQgMGRkNTNjMDktNjQ4Zi00MTZkLTliMTYtM2FmNDdjODY5YmZiZWFiN2FhZGYzMTMwNDNmODg3NWUyOWMxMDBiZTU5MzE="
UPSTASH_REDIS_REST_URL = "https://amusing-seal-38654.upstash.io"